# Site settings
title: Citadel
url: "https://citadelagent.org"
description: Browser-based endpoint security solution
author: Arno van Wouwe
email: citadel@vanwouwe.nl

# Build settings
theme: hacker

# Optional: Better URLs
permalink: pretty

# GitHub metadata
repository: avanwouwe/citadel-browser-agent